#!/usr/bin/env bash
# down.sh — destroy the local kind cluster. All in-cluster state is lost.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
CLUSTER_NAME="equity-local"
CONSOLE_PORT=3030
CONSOLE_PID_FILE="$SCRIPT_DIR/.console.pid"
NATS_PF_PID_FILE="$SCRIPT_DIR/.nats-pf.pid"
STATE_DIR="$SCRIPT_DIR/.state"
BUSINESSES_SNAPSHOT="$STATE_DIR/businesses.yaml"

# ── Safety brake — only ever act on the local kind cluster ──────────────
#
# Every kubectl call in this script (tenant snapshot before nuke, etc.)
# gets pinned to --context=kind-equity-local. Defends against a stray
# `export KUBECONFIG=…` in the operator's shell inadvertently pointing
# these commands at a remote cluster — down.sh would otherwise happily
# read and print namespaces from wherever the current-context lands.
# `kind delete cluster --name equity-local` at the end is already
# --name-scoped, so it can't nuke a remote cluster; this guard covers
# the intermediate read/snapshot steps that could still leak state.
unset KUBECONFIG
export KUBECONFIG="$HOME/.kube/config"
# Hardcode the context name into the wrapper (see up.sh for the full
# reason; short version: `bash -c` subshells inherit exported functions
# but not unexported shell variables).
kubectl() { command kubectl --context="kind-equity-local" "$@"; }
export -f kubectl

# Stop the console. `npm run dev` forks `next-server` as a child process
# that keeps holding :$CONSOLE_PORT if the wrapper is killed alone. That
# orphan then serves 500s from a half-torn .next on the next `up.sh` run.
# Fix: kill the wrapper + children, then sweep by port, then verify.
stop_console() {
  if [ -f "$CONSOLE_PID_FILE" ]; then
    pid=$(cat "$CONSOLE_PID_FILE" 2>/dev/null || echo "")
    if [ -n "$pid" ] && kill -0 "$pid" 2>/dev/null; then
      pkill -TERM -P "$pid" 2>/dev/null || true
      kill -TERM "$pid" 2>/dev/null || true
      echo "✓ Console wrapper (PID $pid) + children signaled."
    fi
    rm -f "$CONSOLE_PID_FILE"
  fi

  # Belt-and-suspenders: anything still holding :$CONSOLE_PORT gets killed.
  # Scoped by port so unrelated Next dev servers on other ports survive.
  local port_pids
  port_pids=$(lsof -ti "tcp:$CONSOLE_PORT" 2>/dev/null || true)
  if [ -n "$port_pids" ]; then
    # shellcheck disable=SC2086
    kill -TERM $port_pids 2>/dev/null || true
    sleep 1
    port_pids=$(lsof -ti "tcp:$CONSOLE_PORT" 2>/dev/null || true)
    if [ -n "$port_pids" ]; then
      # shellcheck disable=SC2086
      kill -KILL $port_pids 2>/dev/null || true
    fi
    echo "✓ Cleared orphan listener(s) on :$CONSOLE_PORT."
  fi

  # Confirm — up.sh's pre-flight is a hard fail if this port is still taken.
  for _ in 1 2 3 4 5; do
    lsof -ti "tcp:$CONSOLE_PORT" >/dev/null 2>&1 || return 0
    sleep 1
  done
  echo "⚠  :$CONSOLE_PORT still bound after teardown — inspect: lsof -i :$CONSOLE_PORT"
}

stop_console

# Kill the NATS port-forward spawned by up.sh so the cluster teardown doesn't
# leave a dangling kubectl process hammering an offline API server.
stop_nats_pf() {
  if [ -f "$NATS_PF_PID_FILE" ]; then
    pid=$(cat "$NATS_PF_PID_FILE" 2>/dev/null || echo "")
    if [ -n "$pid" ] && kill -0 "$pid" 2>/dev/null; then
      kill -TERM "$pid" 2>/dev/null || true
      sleep 1
      kill -0 "$pid" 2>/dev/null && kill -KILL "$pid" 2>/dev/null || true
      echo "✓ NATS port-forward (PID $pid) stopped."
    fi
    rm -f "$NATS_PF_PID_FILE"
  fi
}
stop_nats_pf

if [ -d "$REPO_DIR/console/.next" ]; then
  rm -rf "$REPO_DIR/console/.next"
  echo "✓ Console .next cache cleared."
fi

# Snapshot tenant namespaces BEFORE deleting the cluster so up.sh can
# restore businesses on next boot. Belt-and-suspenders with the git-fork
# restore path — works even when GitHub backup is off or the console's
# commit silently failed. File lives on the host filesystem in
# local/.state/ (gitignored).
if kind get clusters 2>/dev/null | grep -qx "$CLUSTER_NAME"; then
  kubectl config use-context "kind-$CLUSTER_NAME" >/dev/null 2>&1 || true
  tenant_nss=$(kubectl get ns -l equity.io/tenant \
    -o jsonpath='{range .items[*]}{.metadata.name}{"\n"}{end}' 2>/dev/null || true)
  if [ -n "$tenant_nss" ]; then
    mkdir -p "$STATE_DIR"
    {
      echo "# Auto-generated by ./local/down.sh. Captured tenant namespaces so"
      echo "# ./local/up.sh can restore businesses after a teardown. Do NOT"
      echo "# hand-edit — this file is regenerated on every down.sh run."
      while IFS= read -r ns; do
        [ -z "$ns" ] && continue
        slug=$(kubectl get ns "$ns" -o jsonpath='{.metadata.labels.equity\.io/tenant}' 2>/dev/null || echo "")
        name=$(kubectl get ns "$ns" -o jsonpath='{.metadata.labels.equity\.io/tenant-name}' 2>/dev/null || echo "")
        [ -z "$slug" ] && continue
        [ -z "$name" ] && name="$slug"
        printf -- '---\napiVersion: v1\nkind: Namespace\nmetadata:\n  name: %s\n  labels:\n    equity.io/tenant: %s\n    equity.io/tenant-name: %s\n' \
          "$ns" "$slug" "$name"
      done <<< "$tenant_nss"
    } > "$BUSINESSES_SNAPSHOT"
    count=$(grep -c '^  name:' "$BUSINESSES_SNAPSHOT" 2>/dev/null || echo 0)
    echo "✓ Snapshotted $count business namespace(s) → $BUSINESSES_SNAPSHOT"
  fi

  kind delete cluster --name "$CLUSTER_NAME"
  echo "✓ Cluster '$CLUSTER_NAME' deleted."
else
  echo "No cluster named '$CLUSTER_NAME' — nothing to do."
fi
